[package]
name = "klausscc"
version = "0.1.0"
edition = "2021"
authors = ["Graham jones"]
description = "Assembler for Klauss microcontroller defined in FPGA"
repository = "https://github.com/grahamjonesgs/klausscc.git"
readme = "README.md"
license = "MIT"
keywords = ["assembler"]
categories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19"}
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
colored = { version = "2.0.4"}
itertools = { version = "0.11.0", default-features = false, features = ["use_std"] }
serialport = { version = "4.2.1", default-features = true}
tempfile = "3.7.0"
serde = { version = "1.0.177", features = ["derive"] }
serde_json = {version = "1.0.104"}