[package]
name = "klausscc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
clap = "3.1.18"
chrono = "0.4.19"
colored = "2.0.0"
itertools = "0.10.3"

