[package]
name = "klausscc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
clap = "4.0.29"
chrono = "0.4.23"
colored = "2.0.0"
itertools = "0.10.5"
serialport = "4.2.0"
time = "0.3.17"
