[package]
name = "klausscc"
version = "0.1.0"
edition = "2021"
authors = ["Graham jones"]
description = "Assembler for Klauss microcontroller defined in FPGA"
repository = "https://github.com/grahamjonesgs/klausscc.git"
readme = "README.md"
license = "MIT"
keywords = ["assembler"]
categories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4"}
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
colored = { version = "2.0.0"}
itertools = { version = "0.10.5", default-features = false, features = ["use_std"] }
serialport = { version = "4.2.1", default-features = false}
tempfile = "3.6.0"
