[package]
name = "klausscc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
clap = "4.1.0"
chrono = { version = "0.4.23", default-features = false, features = ["std","alloc","clock"] }
colored = "2.0.0"
itertools = "0.10.5"
serialport = { version = "4.2.0", default-features = false}
