[package]
name = "klausscc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
<<<<<<< HEAD
clap = "4.0.18"
chrono = "0.4.22"
=======
clap = "3.2.15"
chrono = "0.4.19"
>>>>>>> master
colored = "2.0.0"
itertools = "0.10.5"
serialport = "4.2.0"
